spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:postgresql://localhost:5433/orders_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  servlet:
    context-path: /api/v1
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
